### ISSUE TITLE
Doubt about your project

### ISSUE THREAD

**Issue by damianlluch** [BenGOsborn/Lazy-Mint-NFT#1]
hello, what do you use ChainLink for in a Lazy Minting? it's not clear to me.
I have a contract erc721 and 1155, to which the client has asked me to add lazy minting, and I am looking for the best alternative to do it.
I look forward to your answer

Best regards

**Comment by BenGOsborn** [comment]
The use of Chainlink in this repository is a concept that I thought of and implemented because I thought it sounded interesting. With my concept, when a user calls the mint function, a chainlink call is made to an external API that generates a new randomized image, uploads it to IPFS, and then returns the link to IPFS. This way, NFT's are truly randomly generated on the fly compared to the conventional method.

What you are looking for is the regular way of lazy minting. What you should do is upload your NFT's initially to IPFS in a folder. Then in your NFT contract first set the maximum amount of minted NFT's to the amount you uploaded to IPFS. Each NFT's tokenId will be incrementally generated, and you can use these tokenId's to point back to the corresponding NFT on IPFS.

e.g. if you have an NFT on IPFS with url: ipfs://example.com/0, you would keep the folder URL"ipfs://example.com/" in your contract, and then your NFT with tokenId 0 would return a URI by appending its tokenId to the end of the folder URL, which would be "ipfs://example.com/" + "0".

Hope this helps.
