### ISSUE TITLE
Is it possible to have Opensea display the lazy-minted NFTs using this code?

### ISSUE THREAD

**Issue by distbit0** [BenGOsborn/Lazy-Mint-NFT#2]
Hi I am wondering whether it is possible to use this code to lazy mint NFTs and list them for sale on Opensea, or whether doing so requires using the Opensea UI and can not be done programatically. Thank you

**Comment by BenGOsborn** [comment]
As far as I am aware, OpenSea autolists minted NFT's in a collection automatically, so if the contract mints a new NFT, I cannot see why it would not be automatically displayed on the OpenSea collection. However, I have not tested this, so I would recommend trying it out on a testnet first before deploying it to mainnet.

I am fairly certain that you will have to interact with OpenSea directly to actually sell the NFT's in your collection. However, I believe you could write a small script to do this for you using the OpenSea API or using Selenium.

**Comment by distbit0** [comment]
I understand and agree that Opensea autolists any *minted* NFTs, but what questioning is whether Opensea lists "lazyminted" NFTs, i.e. NFTs that haven't been minted onchain. I would have thought that in order for this work, you would need to submit the lazymint "coupons" and metadata to an Opensea server API in order for Opensea to become aware of them.

Am I missing something here? :) Thanks

**Comment by BenGOsborn** [comment]
Its been a while since I have properly listed a collection on OpenSea, but I'm pretty sure it works by first calling `totalSupply()` on the ERC721 contract, and then iterating over the minted tokens using `tokenByIndex()`. When an NFT is lazy minted, it automatically increments `totalSupply()`, and therefore from my understanding OpenSea should be able to recognize the lazy minted NFT.

This is just my own speculation and reasoning, as I said the only way to be able to know for real is to actually go and test it on OpenSea which I have not done nor do I plan to. If you decide to give it a try let me know because I'm curious too.

An easy way of testing this would be to deploy an ERC721 to a testnet, add the collection to OpenSea, mint a new one from the contract, and then see if it gets listed on OpenSea automatically.
